# Generated by Django 3.0.3 on 2020-12-08 10:34

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.IntegerField(choices=[(0, 'FEMALE'), (1, 'MALE')])),
            ],
        ),
        migrations.CreateModel(
            name='MarketingData',
            fields=[
                ('md_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cvr', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('breakeven_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('survival_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='MarketingStrategies',
            fields=[
                ('strategy_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'ENABLED'), (1, 'DISABLED')], default=0)),
                ('strategy_name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['status', 'start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RFM',
            fields=[
                ('rfm_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('actual_resp_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rfm_value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=30)),
                ('store_address', models.CharField(max_length=255)),
                ('store_phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=30)),
                ('supplier_address', models.CharField(max_length=255)),
                ('supplier_phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyProductRel',
            fields=[
                ('spr_id', models.AutoField(primary_key=True, serialize=False)),
                ('numbers', models.PositiveSmallIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Products')),
                ('strategy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.MarketingStrategies')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDemandDetails',
            fields=[
                ('store_demand_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_numbers', models.PositiveSmallIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Products')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDemand',
            fields=[
                ('store_demand_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'RECEIVED'), (1, 'ARRIVAL')], default=0)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Stores')),
            ],
            options={
                'ordering': ['created_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingRecords',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('amount', models.PositiveSmallIntegerField()),
                ('shopping_date', models.DateField()),
                ('snackes', models.TextField(blank=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('numbers', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Products')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('security_numbers', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('reorder_point', models.DateField()),
                ('consumption_rate', models.PositiveIntegerField()),
                ('lead_time', models.PositiveSmallIntegerField()),
                ('expiration_duration', models.PositiveSmallIntegerField()),
                ('on_hand_inventory', models.PositiveIntegerField()),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterialRel',
            fields=[
                ('pmr_id', models.AutoField(primary_key=True, serialize=False)),
                ('numbers', models.PositiveSmallIntegerField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.RawMaterial')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'ESTABLISHED'), (1, 'ARRIVAL')], default=0)),
                ('order_amount', models.PositiveIntegerField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.RawMaterial')),
            ],
            options={
                'ordering': ['order_date', 'status'],
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='rfm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.RFM'),
        ),
    ]
