# Generated by Django 3.0.3 on 2020-12-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='marketingdata',
            table='marketing_data',
        ),
        migrations.AlterModelTable(
            name='marketingstrategies',
            table='marketing_strategies',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='productmaterialrel',
            table='product_material_rel',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
        migrations.AlterModelTable(
            name='rawmaterial',
            table='raw_material',
        ),
        migrations.AlterModelTable(
            name='sales',
            table='sales',
        ),
        migrations.AlterModelTable(
            name='shoppingrecords',
            table='shopping_records',
        ),
        migrations.AlterModelTable(
            name='storedemand',
            table='store_demand',
        ),
        migrations.AlterModelTable(
            name='storedemanddetails',
            table='store_demand_details',
        ),
        migrations.AlterModelTable(
            name='stores',
            table='stores',
        ),
        migrations.AlterModelTable(
            name='strategyproductrel',
            table='strategy_product_rel',
        ),
        migrations.AlterModelTable(
            name='suppliers',
            table='suppliers',
        ),
    ]
