# Generated by Django 3.0.3 on 2020-12-09 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0002_auto_20201208_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='rfm_id',
            new_name='rfm',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='productmaterialrel',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='productmaterialrel',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='shoppingrecords',
            old_name='cid',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='storedemand',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='storedemanddetails',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='storedemanddetails',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='strategyproductrel',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='strategyproductrel',
            old_name='strategy_id',
            new_name='strategy',
        ),
        migrations.AlterField(
            model_name='rfm',
            name='actual_resp_rate',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
