# Generated by Django 3.0.3 on 2020-12-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0004_auto_20201221_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingdata',
            name='breakeven_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketingdata',
            name='cvr',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
