# Generated by Django 3.0.3 on 2020-12-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0005_auto_20201222_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stores',
            name='store_region',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
