# Generated by Django 3.0.3 on 2020-12-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0006_auto_20201224_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedemanddetails',
            name='prod_numbers',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
