# Generated by Django 3.0.3 on 2020-12-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0007_auto_20201225_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedemanddetails',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.Products'),
        ),
        migrations.AlterField(
            model_name='storedemanddetails',
            name='store_demand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.StoreDemand'),
        ),
    ]
