# Generated by Django 3.0.3 on 2020-12-25 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0008_auto_20201225_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedemanddetails',
            name='store_demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcdonalds.StoreDemand'),
        ),
    ]
