# Generated by Django 3.0.3 on 2020-12-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_level', models.IntegerField()),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adjentry',
            fields=[
                ('adj_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=22)),
                ('adj_num', models.IntegerField()),
            ],
            options={
                'db_table': 'adjentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cashinbanks',
            fields=[
                ('cash_in_banks_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=10)),
                ('foreign_currency_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ntd_amount', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
            options={
                'db_table': 'cashinbanks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=50)),
                ('parent_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depositaccount',
            fields=[
                ('dep_acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=10)),
                ('foreign_currency_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ntd_amount', models.DecimalField(decimal_places=2, max_digits=22)),
                ('plege', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'depositaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('disclosure_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_amt', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
            options={
                'db_table': 'disclosure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disdetail',
            fields=[
                ('dis_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_name', models.CharField(max_length=50)),
                ('row_amt', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
            options={
                'db_table': 'disdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distitle',
            fields=[
                ('dis_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'distitle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exchangerate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'db_table': 'exchangerate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('grp_id', models.AutoField(primary_key=True, serialize=False)),
                ('grp_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preamt',
            fields=[
                ('pre_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_amt', models.DecimalField(decimal_places=2, max_digits=22)),
                ('adj_mat', models.DecimalField(decimal_places=2, max_digits=22)),
                ('pre_amt', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
            options={
                'db_table': 'preamt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reltrx',
            fields=[
                ('rel_id', models.AutoField(primary_key=True, serialize=False)),
                ('related_amt', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
            options={
                'db_table': 'reltrx',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Systemcode',
            fields=[
                ('system_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_type', models.CharField(max_length=20)),
                ('system_code', models.CharField(max_length=10)),
                ('code_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'systemcode',
                'managed': False,
            },
        ),
    ]
